let headers=[],rows=[],filters=[],sourceFileName='data.csv',mode='table',consoleRecords=[],visibleColumns=[];
const APP_HEADERS=['time','containerId','Host','resultDescription'];
const $=id=>document.getElementById(id),fileEl=$('file'),urlEl=$('fileUrl'),loadUrlBtn=$('loadUrl'),urlMsg=$('urlMsg'),limitEl=$('limit'),rowsControl=$('rowsControl'),showAllBtn=$('showAll'),tableEl=$('table'),statsEl=$('stats'),filtersEl=$('filters'),filterPanel=$('filterPanel'),filterTitle=$('filterTitle'),filterHelp=$('filterHelp'),tableFilterActions=$('tableFilterActions'),resultPanel=$('resultPanel'),resultInfo=$('resultInfo'),exportCsvBtn=$('exportCsv'),columnPicker=$('columnPicker'),columnList=$('columnList'),progress=$('progress'),progressBar=$('progressBar');
function tick(){const n=new Date();$('clockTime').textContent=n.toLocaleTimeString('en-GB',{hour12:false});$('clockDate').textContent=n.toLocaleDateString('en-US',{weekday:'long',day:'2-digit',month:'short',year:'numeric'})}setInterval(tick,1000);tick();
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function detectDelimiter(text){const first=text.split(/\r?\n/,1)[0]||'',candidates=[',',';','\t','|'];let best=',',max=-1;for(const d of candidates){const n=(first.match(new RegExp(d==='|'?'\\|':d==='\t'?'\\t':d,'g'))||[]).length;if(n>max){max=n;best=d}}return best}
function parseCSV(text){if(text.charCodeAt(0)===0xFEFF)text=text.slice(1);const delimiter=detectDelimiter(text),out=[];let row=[],field='',quoted=false;for(let i=0;i<text.length;i++){const ch=text[i];if(quoted){if(ch==='"'){if(text[i+1]==='"'){field+='"';i++}else quoted=false}else field+=ch}else{if(ch==='"')quoted=true;else if(ch===delimiter){row.push(field);field=''}else if(ch==='\n'){row.push(field);out.push(row);row=[];field=''}else if(ch!=='\r')field+=ch}}if(field!==''||row.length){row.push(field);out.push(row)}while(out.length&&out[out.length-1].every(x=>x===''))out.pop();return out}
function normalizeHeaders(raw){const seen={};return raw.map((h,i)=>{let name=String(h||'').trim()||`Column ${i+1}`;seen[name]=(seen[name]||0)+1;return seen[name]>1?`${name} (${seen[name]})`:name})}
function setupFilterUi(title,help){filterTitle.textContent=title;filterHelp.textContent=help;filtersEl.style.display='flex';tableFilterActions.style.display='flex'}
function setTableMode(){mode='table';rowsControl.style.display='flex';showAllBtn.style.display='inline-block';setupFilterUi('Filters','Multiple filters are combined with AND. For > and <, numeric values are compared as numbers; other values are compared as text.');exportCsvBtn.style.display='inline-block';columnPicker.style.display='block'}
function renderColumnPicker(){columnList.innerHTML='';headers.forEach((h,i)=>{const label=document.createElement('label'),box=document.createElement('input');box.type='checkbox';box.checked=visibleColumns.includes(i);box.onchange=()=>{if(box.checked){if(!visibleColumns.includes(i))visibleColumns.push(i)}else visibleColumns=visibleColumns.filter(x=>x!==i);visibleColumns.sort((a,b)=>a-b);render()};label.append(box,document.createTextNode(h));columnList.appendChild(label)})}
function showData(name,displayName,extra=''){setTableMode();filters=[];filtersEl.innerHTML='';sourceFileName=name||'data.csv';filterPanel.style.display='block';resultPanel.style.display='block';statsEl.innerHTML=`<span class="badge">${esc(displayName||name)}</span><span>${rows.length.toLocaleString()} rows</span><span>${headers.length} columns</span>${extra}`;renderColumnPicker();addFilter();render()}
function loadCsvText(text,name){visibleColumns=[];const parsed=parseCSV(text);if(!parsed.length){alert('CSV is empty.');return}headers=normalizeHeaders(parsed[0]);rows=parsed.slice(1).map(r=>headers.map((_,i)=>r[i]??''));visibleColumns=headers.map((_,i)=>i);showData(name,name)}
function normalizeJsonValue(value){if(value===null||value===undefined)return '';if(typeof value==='object')return JSON.stringify(value);return value}
function parseJsonLines(text){const records=[],errors=[];text.split(/\r?\n/).forEach((raw,i)=>{const line=raw.trim();if(!line)return;try{const v=JSON.parse(line);if(v&&typeof v==='object'&&!Array.isArray(v))records.push(v);else errors.push(`Line ${i+1}: Expected JSON object`)}catch(e){errors.push(`Line ${i+1}: ${e.message}`)}});return {records,errors}}
function isApplicationLog(records){return records.some(r=>r.resultDescription!==undefined||r.containerId!==undefined)}
function isHttpLog(records){return records.some(r=>r.properties!==undefined||r.EventTime!==undefined||r.EventIpAddress!==undefined)}
function loadHttpLog(records,errors,name){const converted=records.map(record=>{const row={time:record.time??'',EventTime:record.EventTime??'',category:record.category??'',Host:record.Host??'',EventIpAddress:record.EventIpAddress??''};const props=record.properties;if(props!==undefined&&props!==null&&props!==''){if(typeof props==='string'){try{const parsedProps=JSON.parse(props);if(parsedProps&&typeof parsedProps==='object'&&!Array.isArray(parsedProps))Object.assign(row,parsedProps);else row.properties=props}catch{row.properties=props}}else if(typeof props==='object'&&!Array.isArray(props))Object.assign(row,props);else row.properties=props}return row});headers=[...new Set(converted.flatMap(r=>Object.keys(r)))].sort();rows=converted.map(r=>headers.map(h=>normalizeJsonValue(r[h])));visibleColumns=headers.map((_,i)=>i);const csvName=(name||'data.json').replace(/\.(jsonl?|ndjson)$/i,'')+'.csv';showData(csvName,name,`<span>HTTP JSON converted${errors.length?` · ${errors.length} invalid line${errors.length===1?'':'s'} skipped`:''}</span>`)}
function loadConsoleLog(records,errors,name){mode='console';consoleRecords=records.map(r=>({time:r.time??'',containerId:r.containerId??'',Host:r.Host??'',resultDescription:r.resultDescription??''}));headers=[];rows=[];visibleColumns=[];filters=[];filtersEl.innerHTML='';sourceFileName=name||'data.json';rowsControl.style.display='flex';showAllBtn.style.display='inline-block';setupFilterUi('Application log filters','Filter application logs by time, containerId, Host or resultDescription. Multiple filters are combined with AND.');exportCsvBtn.style.display='none';columnPicker.style.display='none';filterPanel.style.display='block';resultPanel.style.display='block';statsEl.innerHTML=`<span class="badge">${esc(name)}</span><span>${consoleRecords.length.toLocaleString()} application log records</span>${errors.length?`<span>${errors.length} invalid line${errors.length===1?'':'s'} skipped</span>`:''}`;addFilter();render()}
function loadJsonText(text,name){let records=[],errors=[];try{const parsed=JSON.parse(text);if(Array.isArray(parsed))records=parsed.filter(v=>v&&typeof v==='object'&&!Array.isArray(v));else if(parsed&&typeof parsed==='object')records=[parsed]}catch{const p=parseJsonLines(text);records=p.records;errors=p.errors}if(!records.length){alert('No JSON records found.');return}if(isApplicationLog(records)){loadConsoleLog(records,errors,name);return}if(isHttpLog(records)){loadHttpLog(records,errors,name);return}const converted=records;headers=[...new Set(converted.flatMap(r=>Object.keys(r)))];rows=converted.map(r=>headers.map(h=>normalizeJsonValue(r[h])));visibleColumns=headers.map((_,i)=>i);showData((name||'data.json').replace(/\.json$/i,'.csv'),name)}
function loadSourceText(text,name,type=''){if(/json|ndjson/i.test(type)||/\.(json|jsonl|ndjson)$/i.test(name))loadJsonText(text,name);else loadCsvText(text,name)}
function addFilter(){const row=document.createElement('div');row.className='filter-row';const fields=mode==='console'?APP_HEADERS:headers;row.innerHTML=`<select class="select field">${fields.map(h=>`<option value="${esc(h)}">${esc(h)}</option>`).join('')}</select><select class="select op"><option value="includes">includes</option><option value="=">=</option><option value=">">&gt;</option><option value="<">&lt;</option></select><input class="input value" placeholder="Filter value"><button class="btn btn-danger remove">Remove</button>`;row.querySelector('.remove').onclick=()=>{row.remove();render()};row.querySelectorAll('select,input').forEach(el=>el.oninput=render);filtersEl.appendChild(row)}
function compareValues(a,op,b,field=''){a=String(a??'');b=String(b??'');if(op==='includes')return a.toLowerCase().includes(b.toLowerCase());if(field==='time'){const at=Date.parse(a),bt=Date.parse(b);if(!Number.isNaN(at)&&!Number.isNaN(bt)){if(op==='=')return at===bt;if(op==='>')return at>bt;if(op==='<')return at<bt}}const an=Number(a),bn=Number(b),numeric=!Number.isNaN(an)&&!Number.isNaN(bn)&&b.trim()!=='';const x=numeric?an:a.toLowerCase(),y=numeric?bn:b.toLowerCase();if(op==='=')return x==y;if(op==='>')return x>y;if(op==='<')return x<y;return true}
function activeFilters(){return [...filtersEl.querySelectorAll('.filter-row')].map(r=>({field:r.querySelector('.field').value,op:r.querySelector('.op').value,value:r.querySelector('.value').value})).filter(f=>f.value!=='')}
function render(){const af=activeFilters();if(mode==='console'){const filtered=consoleRecords.filter(r=>af.every(f=>compareValues(r[f.field],f.op,f.value,f.field))),limit=Math.max(1,Number(limitEl.value)||100),shown=filtered.slice(0,limit);tableEl.innerHTML=`<pre class="text-log">${esc(shown.map(r=>JSON.stringify(r)).join('\n'))}</pre>`;resultInfo.innerHTML=`<span>${filtered.length.toLocaleString()} matching records</span><span>Showing ${shown.length.toLocaleString()}</span>`;return}const filtered=rows.filter(row=>af.every(f=>{const i=headers.indexOf(f.field);return compareValues(row[i],f.op,f.value,f.field)})),limit=Math.max(1,Number(limitEl.value)||100),shown=filtered.slice(0,limit),cols=visibleColumns;let html='<div class="table-wrap"><table><thead><tr>'+cols.map(i=>`<th>${esc(headers[i])}</th>`).join('')+'</tr></thead><tbody>';html+=shown.length?shown.map(r=>'<tr>'+cols.map(i=>`<td title="${esc(r[i])}">${esc(r[i])}</td>`).join('')+'</tr>').join(''):`<tr><td class="empty" colspan="${Math.max(1,cols.length)}">No matching rows</td></tr>`;html+='</tbody></table></div>';tableEl.innerHTML=html;resultInfo.innerHTML=`<span>${filtered.length.toLocaleString()} matching rows</span><span>Showing ${shown.length.toLocaleString()}</span><span>${cols.length}/${headers.length} columns visible</span>`}
function formatBytes(n){if(!Number.isFinite(n)||n<0)return '';if(n<1024)return n+' B';if(n<1024*1024)return (n/1024).toFixed(1)+' KB';return (n/1024/1024).toFixed(1)+' MB'}
async function responseTextWithProgress(response){if(!response.body||!response.body.getReader)return response.text();const total=Number(response.headers.get('content-length')||0),reader=response.body.getReader(),decoder=new TextDecoder(),parts=[];let received=0;progress.style.display='block';progressBar.style.width='0%';while(true){const {done,value}=await reader.read();if(done)break;received+=value.byteLength;parts.push(decoder.decode(value,{stream:true}));if(total>0){const pct=Math.min(100,received/total*100);progressBar.style.width=pct.toFixed(1)+'%';urlMsg.textContent=`Browser is downloading... ${pct.toFixed(0)}% · ${formatBytes(received)} / ${formatBytes(total)}`}else{progressBar.style.width='100%';urlMsg.textContent=`Browser is downloading... ${formatBytes(received)}`}}parts.push(decoder.decode());return parts.join('')}
fileEl.onchange=async()=>{const f=fileEl.files[0];if(!f)return;loadSourceText(await f.text(),f.name,f.type)};
loadUrlBtn.onclick=async()=>{const raw=urlEl.value.trim();if(!raw)return alert('Paste a file URL first.');let parsed;try{parsed=new URL(raw);if(!/^https?:$/.test(parsed.protocol))throw new Error('Only http/https URLs are supported.')}catch(e){return alert('Invalid URL: '+e.message)}loadUrlBtn.disabled=true;loadUrlBtn.textContent='Loading...';urlMsg.textContent='Browser is downloading the file...';progress.style.display='block';progressBar.style.width='0%';try{const response=await fetch(parsed.href,{cache:'no-store'});if(!response.ok)throw new Error('HTTP '+response.status);const text=await responseTextWithProgress(response);const disposition=response.headers.get('content-disposition')||'',m=disposition.match(/filename\*?=(?:UTF-8''|["']?)([^"';]+)/i),dispositionName=m?decodeURIComponent(m[1].replace(/["']/g,'')):'';const source=response.url||parsed.href,name=dispositionName||(new URL(source).pathname.split('/').pop()||'download');loadSourceText(text,name,response.headers.get('content-type')||'');urlMsg.textContent='Loaded: '+name;progressBar.style.width='100%'}catch(e){urlMsg.textContent='Could not download this URL: '+e.message;progress.style.display='none'}finally{loadUrlBtn.disabled=false;loadUrlBtn.textContent='Load URL'}};
$('addFilter').onclick=()=>addFilter();$('clearFilters').onclick=()=>{filtersEl.innerHTML='';addFilter();render()};$('selectAllColumns').onclick=()=>{visibleColumns=headers.map((_,i)=>i);renderColumnPicker();render()};$('deselectAllColumns').onclick=()=>{visibleColumns=[];renderColumnPicker();render()};showAllBtn.onclick=()=>{limitEl.value=Number.MAX_SAFE_INTEGER;render()};limitEl.oninput=render;
$('clear').onclick=()=>{headers=[];rows=[];filters=[];consoleRecords=[];visibleColumns=[];mode='table';sourceFileName='data.csv';fileEl.value='';urlEl.value='';urlMsg.textContent='';statsEl.innerHTML='';filterPanel.style.display='none';resultPanel.style.display='none';columnPicker.style.display='none';tableEl.innerHTML='';filtersEl.innerHTML='';progress.style.display='none';progressBar.style.width='0%'};
exportCsvBtn.onclick=()=>{if(mode!=='table')return;const af=activeFilters(),filtered=rows.filter(row=>af.every(f=>{const i=headers.indexOf(f.field);return compareValues(row[i],f.op,f.value,f.field)}));const csv='\uFEFF'+[headers,...filtered].map(row=>row.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(',')).join('\r\n'),blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=sourceFileName.replace(/\.(jsonl?|ndjson)$/i,'')||'export.csv';if(!/\.csv$/i.test(a.download))a.download+='.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
